# Generated by Django 5.1.2 on 2024-10-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_product_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_db',
            name='Category_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
