# Generated by Django 5.1.2 on 2024-10-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_product_db_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blog_Data', models.CharField(blank=True, max_length=100, null=True)),
                ('Blog_Image', models.ImageField(blank=True, null=True, upload_to='blogimg')),
            ],
        ),
    ]
