# Generated by Django 5.1.2 on 2024-11-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_cartdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdb',
            name='PricePerItem',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
