# Generated by Django 5.1.2 on 2024-11-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_orderdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdb',
            name='Prod_Img',
            field=models.ImageField(blank=True, null=True, upload_to='cart_Img'),
        ),
    ]
