# Generated by Django 5.1.2 on 2024-11-20 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0006_cartdb_prod_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_db',
            old_name='Emailaddress',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='contact_db',
            old_name='Firstname',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='contact_db',
            name='Lastname',
        ),
    ]
